name: Build binaries and release
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION_STRING: ${{ github.ref_name }}
      REPO_URL: github.com/noAbbreviation/approxima
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.23"
      - run: go version
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          go get -u .
          go mod tidy
      - name: Build For Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o "approxima-${GOOS}_${GOARCH}" \
          -ldflags="-s -X ${REPO_URL}/main.versionString=${VERSION_STRING}" \
          .
          chmod +x "approxima-${GOOS}_${GOARCH}"
      - name: Build For MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -o "approxima-${GOOS}_${GOARCH}" \
          -ldflags="-s -X ${REPO_URL}/main.versionString=${VERSION_STRING}" \
          .
          chmod +x "approxima-${GOOS}_${GOARCH}"
      - name: Build For Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          go build -o "approxima-${GOOS}_${GOARCH}.exe" \
          -ldflags="-s -X ${REPO_URL}/main.versionString=${VERSION_STRING}" \
          .
          chmod +x "approxima-${GOOS}_${GOARCH}.exe"
      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          make_latest: true
          name: ${{ github.ref_name }}
          files: |
            approxima-*
